name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Custom image tag'
        required: false
        default: 'latest'

env:
  # Container registry settings
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  # Alternative registries (uncomment as needed)
  # DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  # AWS_REGION: us-east-1
  # GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # DockerHub (optional)
      # - name: Log in to DockerHub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # AWS ECR (optional)
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ env.AWS_REGION }}
      #
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      - name: Sanitize branch name for Docker tag
        id: branch
        run: |
          # Get branch name and sanitize it for Docker tag use
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          
          # Sanitize branch name: lowercase, replace invalid chars with dash, remove leading/trailing dashes
          CLEAN_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g' | sed 's/^-\+\|-\+$//g' | sed 's/-\+/-/g')
          
          # Ensure we have a valid branch name, fallback to 'unknown' if empty
          if [ -z "$CLEAN_BRANCH" ] || [ "$CLEAN_BRANCH" = "-" ]; then
            CLEAN_BRANCH="unknown"
          fi
          
          # Limit length to 63 characters (Docker tag limit) and ensure no trailing dash
          CLEAN_BRANCH=$(echo "$CLEAN_BRANCH" | cut -c1-63 | sed 's/-$//g')
          
          # Final check: if we ended up with empty string after trimming, use fallback
          if [ -z "$CLEAN_BRANCH" ]; then
            CLEAN_BRANCH="unknown"
          fi
          
          echo "original=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "sanitized=$CLEAN_BRANCH" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.image_tag || 'latest' }},enable=${{ github.event.inputs.image_tag != '' }}
            type=raw,value=${{ steps.branch.outputs.sanitized }}-{{sha}},enable=${{ steps.branch.outputs.sanitized != '' }}
          flavor: |
            latest=auto

      - name: Debug metadata output
        run: |
          echo "Branch info:"
          echo "  Original: ${{ steps.branch.outputs.original }}"
          echo "  Sanitized: ${{ steps.branch.outputs.sanitized }}"
          echo ""
          echo "Generated tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Generated labels:"
          echo "${{ steps.meta.outputs.labels }}"
          echo ""
          echo "Event context:"
          echo "  Event name: ${{ github.event_name }}"
          echo "  Ref name: ${{ github.ref_name }}"
          echo "  Head ref: ${{ github.head_ref }}"
          echo "  Is default branch: ${{ github.ref == 'refs/heads/main' }}"

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.chatbot
          # Use single platform for PR builds (when loading locally), multi-platform for pushes
          platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          # Push to registry for main branch pushes and releases, load locally for PRs
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        if: github.event_name != 'pull_request' && steps.meta.outputs.version != ''
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version || 'latest' }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Deploy to preview environment
        run: |
          echo "Deploy preview for PR #${{ github.event.pull_request.number }}"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}"

  scan-vulnerabilities:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
