name: Python and R CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install main application dependencies
          pip install -r requirements-chatbot.txt || pip install -r requirements.txt || true
          # Install test dependencies
          pip install -r tests/requirements-test.txt
          # Install Playwright browsers (only chromium for faster CI)
          playwright install chromium
      - name: Validate API key configuration
        run: python validate_env_keys.py
      - name: Run Python tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest || exit 1
          else
            echo "No Python tests found. Skipping."
          fi

  r-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install R package dependencies
        run: |
          if [ -f DESCRIPTION ]; then
            Rscript -e 'install.packages("devtools", repos="https://cran.rstudio.com")'
            Rscript -e 'devtools::install_deps(dep=TRUE)'
          else
            echo "No R DESCRIPTION file found. Skipping dependency install."
          fi
      - name: Run R CMD check
        run: |
          if [ -f DESCRIPTION ]; then
            Rscript -e 'devtools::check()'
          else
            echo "No R package to check. Skipping."
          fi
